_wandb:
    value:
        cli_version: 0.23.1
        e:
            vqfh4hstq8pflal8f3sd9m12mm1zgmzj:
                apple:
                    ecpuCores: 4
                    gpuCores: 7
                    memoryGb: 8
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "8589934592"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "217711423488"
                email: rajceo2031@gmail.com
                executable: /opt/miniconda3/envs/game_rl/bin/python
                host: Yuvrajs-MacBook-Air-6034.local
                memory:
                    total: "8589934592"
                os: macOS-26.1-arm64-arm-64bit
                program: /Users/yuvrajsingh9886/Desktop/youtube-dueling-ai-pong/./train.py
                python: CPython 3.10.0
                root: /Users/yuvrajsingh9886/Desktop/youtube-dueling-ai-pong
                startedAt: "2025-12-07T05:28:46.563753Z"
                writerId: vqfh4hstq8pflal8f3sd9m12mm1zgmzj
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.10.0
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
algorithm:
    value: DQN
batch_size:
    value: 32
checkpoint_pool:
    value: 5
episodes:
    value: 3000
epsilon:
    value: 1
epsilon_decay:
    value: 0.995
gamma:
    value: 0.99
hidden_layer:
    value: 756
learning_rate:
    value: 0.0001
max_buffer_size:
    value: 200000
max_episode_steps:
    value: 2000
min_epsilon:
    value: 0.15
target_update_interval:
    value: 10000
